version: "2"
services:
  web:
    build:
      context: "../"
      dockerfile: Dockerfile-test
    volumes:
      - "../app:/src/app"
    ports:
      - "3030:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017" 
