version: "2"
services:
  web:
    build:
      context: "../"
      dockerfile: Dockerfile-development
    volumes:
      - "../app:/src/app"
    restart: always
    ports:
      - "3030:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always